-- Dados de exemplo pra desenvolvimento local. A Supabase CLI roda este
-- arquivo automaticamente depois das migrations em `supabase db reset`;
-- pra aplicar manualmente num projeto remoto, cole o conteúdo no SQL
-- Editor do Studio ou rode via `supabase db execute` (não é um substituto
-- de admin real — gerenciar escola/turma em produção é via Studio, ver
-- seção "Fora do escopo" do brief).
--
-- Escolas reais dos distritos de Lisboa e Setúbal (fonte: DGAE/ME, rede
-- de agrupamentos de escolas e escolas não agrupadas 2025/2026) — 222
-- agrupamentos/escolas, cada um com uma turma por ano do 5º ao 12º ano.
with novas_escolas as (
  insert into public.escolas (nome, endereco)
  values
  ('Agrupamento de Escolas Visconde de Chanceleiros, Alenquer', 'Alenquer, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Carregado, Alenquer', 'Alenquer, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Damião de Goes, Alenquer', 'Alenquer, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Abrigada, Alenquer', 'Alenquer, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Azambuja', 'Azambuja, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Vale Aveiras, Azambuja', 'Azambuja, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Alto da Azambuja', 'Azambuja, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Cadaval', 'Cadaval, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. Lourenço Vicente, Lourinhã', 'Lourinhã, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Lourinhã', 'Lourinhã, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Arruda dos Vinhos', 'Arruda dos Vinhos, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Venda do Pinheiro, Mafra', 'Mafra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Ericeira, Mafra', 'Mafra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Professor Armando Lucena, Mafra', 'Mafra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Mafra', 'Mafra, distrito de Lisboa, Portugal'),
  ('Escola Secundária José Saramago, Mafra', 'Mafra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Joaquim Inácio da Cruz Sobral, Sobral do Monte Agraço', 'Sobral de Monte Agraço, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de São Gonçalo, Torres Vedras', 'Torres Vedras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Henriques Nogueira, Torres Vedras', 'Torres Vedras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Padre Vítor Melícias, Torres Vedras', 'Torres Vedras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Madeira Torres, Torres Vedras', 'Torres Vedras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Alfornelos, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Almeida Garrett, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas José Cardoso Pires, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Pioneiros da Aviação Portuguesa, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Cardoso Lopes, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Miguel Torga, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Amadora Oeste, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Fernando Namora, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Damaia, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Dr. Azevedo Neves, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Mães D´Agua, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. João V, Amadora', 'Amadora, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Ibn Mucana, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de São João do Estoril, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Alapraia, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Parede, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Alcabideche, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Matilde Rosa Araújo, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Carcavelos, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Frei Gonçalo de Azevedo, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Alvide, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Cidadela, Cascais', 'Cascais, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Padre Bartolomeu de Gusmão, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Vergílio Ferreira, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Restelo, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Patrício Prazeres, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Professor Lindley Cintra - Lumiar, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas das Olaias, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Fernando Pessoa, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Marquesa de Alorna, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Francisco de Arruda, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. Dinis, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Luís António Verney, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Bairro Padre Cruz, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Piscinas - Olivais, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas das Laranjeiras, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Santa Maria dos Olivais, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Manuel da Maia, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Alto do Lumiar, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Rainha D. Leonor, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Luís de Camões, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Alvalade, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Benfica, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Quinta de Marrocos, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Pintor Almada Negreiros, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Passos Manuel, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Nuno Gonçalves, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. Filipa de Lencastre, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Gil Vicente, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Eça de Queirós, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Secundária Maria Amália Vaz de Carvalho, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Secundária Camões, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Secundária Fonseca Benevides, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Secundária Marquês de Pombal, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Artística António Arroio, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Artística do Instituto Gregoriano de Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Artística de Dança do Conservatório Nacional, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Artística de Música do Conservatório Nacional, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Profissional de Ciências Geográficas, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Secundária Rainha Dona Amélia, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Escola Secundária Pedro Nunes, Lisboa', 'Lisboa, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Camarate - D. Nuno Álvares Pereira, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas 4 de Outubro, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Catujal - Unhos, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Portela e Moscavide, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Luís de Sttau Monteiro, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas João Villaret, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas General Humberto Delgado, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas José Afonso, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas da Bobadela, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Santa Iria de Azóia, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de São João da Talha, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Eduardo Gageiro, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Maria Keil, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Escola Secundária de Camarate, Loures', 'Loures, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Braamcamp Freire', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Pedro Alexandrino - Póvoa de Santo Adrião, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Vasco Santana, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Moinhos da Arroja, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Adelaide Cabette, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas a Sudoeste de Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Caneças, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. Dinis, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Escola Secundária da Ramada, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Escola Profissional Agrícola D. Dinis - Paiã, Odivelas', 'Odivelas, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Aquilino Ribeiro, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de São Bruno, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Carnaxide, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Carnaxide - Portela, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Miraflores, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Paço de Arcos, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Conde de Oeiras, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de São Julião da Barra, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Linda-a-Velha e Queijas, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Santa Catarina, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Escola Secundária da Quinta do Marquês, Oeiras', 'Oeiras, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. João II, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Leal da Câmara, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Alto dos Moinhos, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Aqua Alba, Agualva, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Mem Martins, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. Carlos I, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Alfredo da Silva, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Lapiás, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Algueirão, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Agualva Mira Sintra, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Ferreira de Castro, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Professor Agostinho da Silva, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Visconde de Juromenha, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Queluz-Belas, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Escultor Francisco dos Santos, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Miguel Torga, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Massamá, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Ruy Belo, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Monte da Lua, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. Maria II, Sintra', 'Sintra, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Bom Sucesso, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Alves Redol, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Póvoa de Santa Iria, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Alhandra, Sobralinho e São João dos Montes, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Vialonga, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Pedro Jacques de Magalhães, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas Professor Reynaldo dos Santos, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas do Forte da Casa, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas D. António de Ataíde, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Escola Secundária Gago Coutinho, Alverca do Ribatejo, Vila Franca de Xira', 'Vila Franca de Xira, distrito de Lisboa, Portugal'),
  ('Agrupamento de Escolas de Alcochete', 'Alcochete, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas da Trafaria, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Elias Garcia, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas do Monte da Caparica, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas da Caparica, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Emídio Navarro, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas António Gedeão, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Romeu Correia, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Miradouro de Alfazina, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Daniel Sampaio, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Professor Ruy Luís Gomes, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Anselmo de Andrade, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Carlos Gargaté, Charneca da Caparica, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Francisco Simões, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Escola Secundária de Cacilhas-Tejo, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Escola Secundária Fernão Mendes Pinto, Pragal, Almada', 'Almada, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Santo André, Barreiro', 'Barreiro, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Santo António, Barreiro', 'Barreiro, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas do Barreiro', 'Barreiro, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Augusto Cabrita, Barreiro', 'Barreiro, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Casquilhos, Barreiro', 'Barreiro, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Álvaro Velho, Barreiro', 'Barreiro, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Alfredo da Silva, Barreiro', 'Barreiro, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas D. João I, Moita', 'Moita, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas da Baixa da Banheira, Vale da Amoreira, Moita', 'Moita, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas José Afonso, Moita', 'Moita, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Mouzinho da Silveira, Moita', 'Moita, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Fragata do Tejo, Moita', 'Moita, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas da Moita', 'Moita, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Pegões, Canha e Santo Isidro, Montijo', 'Montijo, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas do Montijo', 'Montijo, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Poeta Joaquim Serra, Montijo', 'Montijo, distrito de Setúbal, Portugal'),
  ('Escola Secundária Jorge Peixinho, Montijo', 'Montijo, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas José Saramago, Palmela', 'Palmela, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Palmela', 'Palmela, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas José Maria dos Santos, Palmela', 'Palmela, distrito de Setúbal, Portugal'),
  ('Escola Secundária de Palmela', 'Palmela, distrito de Setúbal, Portugal'),
  ('Escola Secundária de Pinhal Novo, Palmela', 'Palmela, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Vale de Milhaços, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Pinhal de Frades, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Nun´Álvares, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Dr. António Augusto Louro, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Pedro Eanes Lobato, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas João de Barros, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Terras de Larus, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Paulo da Gama, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Escola Secundária Alfredo dos Reis Silveira, Cavadas, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Escola Secundária Dr. José Afonso, Arrentela, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Escola Secundária Manuel Cargaleiro, Amora, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Escola Secundária da Amora, Seixal', 'Seixal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Maria do Carmo Serrote, Sesimbra', 'Sesimbra, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Michel Giacometti, Sesimbra', 'Sesimbra, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Sampaio, Sesimbra', 'Sesimbra, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Navegador Rodrigues Soromenho, Sesimbra', 'Sesimbra, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Boa Água, Sesimbra', 'Sesimbra, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Sebastião da Gama, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Ordem de Santiago, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Azeitão, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Luísa Todi, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Barbosa du Bocage, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Lima de Freitas, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Escola Secundária Dom Manuel Martins, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Escola Secundária du Bocage, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Escola Secundária D. João II, Setúbal', 'Setúbal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Alcácer do Sal', 'Alcácer do Sal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Torrão, Alcácer do Sal', 'Alcácer do Sal, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Grândola', 'Grândola, distrito de Setúbal, Portugal'),
  ('Escola Profissional de Desenvolvimento Rural de Grândola', 'Grândola, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas Prof. Arménio Lança, Santiago do Cacém', 'Santiago do Cacém, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Cercal do Alentejo, Santiago do Cacém', 'Santiago do Cacém, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Santiago do Cacém', 'Santiago do Cacém, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Santo André, Santiago do Cacém', 'Santiago do Cacém, distrito de Setúbal, Portugal'),
  ('Agrupamento de Escolas de Sines', 'Sines, distrito de Setúbal, Portugal'),
  ('Escola Secundária Poeta Al Berto, Sines', 'Sines, distrito de Setúbal, Portugal')
  returning id, nome
)
insert into public.turmas (escola_id, nome, serie_ano)
select ne.id, 'Turma Única', ano
from novas_escolas ne
cross join (values ('5º ano'), ('6º ano'), ('7º ano'), ('8º ano'), ('9º ano'), ('10º ano'), ('11º ano'), ('12º ano')) as anos(ano);
